---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gebetaya/public_html/taxi.gebetacloud.com
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -r assets $DEPLOYPATH/
    - /bin/cp -r img $DEPLOYPATH/
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/cp icon.png $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/